version: "3"

services:
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network

  app:
    build:
      context: node
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 50s -- bash start.sh
    # entrypoint: wait-for db:3306 -t 40 -- ./start.sh
    volumes:
      - ./node:/usr/src/app
    restart: always
    tty: true
    ports:
      - "81:3000"
    networks:
      - node-network
    depends_on:
      - db

  nginx:
    build: ./nginx
    entrypoint: dockerize -wait tcp://app:3000 -timeout 50s /docker-entrypoint.sh "nginx" "-g" "daemon off;"
    container_name: nginx
    restart: always
    tty: true
    ports:
      - "8080:80"
    networks:
      - node-network
    depends_on:
      - app

networks:
  node-network:
    driver: bridge
